name: Build and Push Nest Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: sentimental-api
      PROJECT_ID: sentimental-analysis-api
      REGION: southamerica-east1
      SERVICE: sentimental-api
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate gcloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      run: |-
        docker tag $IMAGE_NAME:latest $REGION-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker push $REGION-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest

    - name: Deploy container image to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: sentimental-api
        image: southamerica-east1-docker.pkg.dev/sentimental-analysis-api/images/sentimental-api:latest
        region: southamerica-east1
        port: ${{ secrets.APP_PORT }}
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}